### ISSUE TITLE
High battery consumption and   wifi does not work

### ISSUE THREAD

**Issue by renantd** [Amin-0-1/hackintosh-Dell-g3-15-3590-#11]
Hey, Amin!
I did an installation on your EFI and it works almost everything except the wifi. And also the gpu is enabled generating a high consumption in the battery (1%, every 30s ~ 1m).

I include the following text in config.plist:

`<key>AddProperties</key>
    <array>
        <dict>
            <key>Device</key>
            <string>NVidia</string>
            <key>Disabled</key>
            <false/>
            <key>Key</key>
            <string>name</string>
            <key>Value</key>
            <data>
            I2Rpc3BsYXk=
            </data>
        </dict>
        <dict>
            <key>Device</key>
            <string>NVidia</string>
            <key>Disabled</key>
            <false/>
            <key>Key</key>
            <string>IOName</string>
            <key>Value</key>
            <string>#display</string>
        </dict>
        <dict>
            <key>Device</key>
            <string>NVidia</string>
            <key>Disabled</key>
            <false/>
            <key>Key</key>
            <string>class-code</string>
            <key>Value</key>
            <data>
            /////w==
            </data>
        </dict>
    </array>
`
com estas tags , o consumo da bateria normalizou . Acho que seria bom ,você incluir isto no config.plist

**Comment by Amin-0-1** [comment]
That is a good tip from you brother, thank you. Regarding the Wifi note that the responsible kext for making it work is AirportItlwm.kext and that is currently under development and has some issues, if you want another way for stability you can head to use Itlwm.kext and use heliport.app in startup booting app it is kinda stable 
keep in touch to make a good stable efi , if you found a problem let me know

**Comment by renantd** [comment]
OK . I understand . In my case, the wifi module that comes from the factory is the qualcomm dw1810, and from what I researched it is not supported and I use the Bigsur macos. Thanks for the clarification.

**Comment by brenosabino** [comment]
@renantd are you using opencore as well? my config.plist is like the image below, ive also disabled the kexts AirportItlwm, IntelBluetoothFirmware and IntelBluetoothInjector since my wifi card is incompatible and im using a usb wifi adapter. And im using voltageshift to undervolt the cpu but still im only getting 2 hours battery.

![Screen Shot 2021-02-28 at 12 50 52](https://user-images.githubusercontent.com/4714900/109424722-a2180980-79c3-11eb-86dc-9b030ee737c8.png)

**Comment by Amin-0-1** [comment]
@brenosabino make sure if that period is lower than in windows indeed or it is a hardware issue, as my battery is almost dead also in windows then it is not a measure that it takes small period of time on battery with macos

**Comment by Amin-0-1** [comment]
@renantd @brenosabino try it right now and keep in touch letting me know if the battery life become better or not

**Comment by renantd** [comment]
For me, after I disabled the nvidia driver, the battery consumes a little more than windows but nothing high, I consider it normal for hackinstosh.
I'm using opencore too, but I didn't undervolt, I just disabled turboBoost on the bios.

**Comment by Amin-0-1** [comment]
@renantd I meant that I've updated my repo with the latest oc beta and tried to missing up with some stuff in pm and it seems to be perfect with me right now, my only 2 problems are that "awaking from sleep needs more than one key pressed & second and most annoying to me is when I put it to sleep when unplugged and trying to wake it wakes okay but sometimes the laptop shuts down automatically"

**Comment by renantd** [comment]
Weird . for me the only thing that doesn't work is the wifi, because I don't have the intel wifi module. The battery works normal now. When I leave the macos in "sleep / hibernate", it recharges normally by pressing a key. Your Efi for me is almost perfect. In your case I would try to do a "clean" installation and test again. If the problem persists, it may be a problem with your kext keyboard.
I installed macos with some changes, maybe that made my installation more "more compatible"

**Comment by Amin-0-1** [comment]
lol, you are not the only one how says that my efi is perfect for them , I made it myself and it is not perfect for me 😆

**Comment by rmwalk** [comment]
@Amin-0-1 I got the same issue with the awaking from sleep when unplugged. In fact it never actually works, the screen just stays turned off but the keyboard apparently works because it lights up and I can hear the OS sounds when pressing some keys. Did you manage to get it working?

**Comment by Amin-0-1** [comment]
@rmwalk  yup it works with me okay now , give it a try

**Comment by rmwalk** [comment]
@Amin-0-1 just tried it, still the same problem here. Not a huge deal though, I never actually use sleep, just wanted to check if it would work.

**Comment by Amin-0-1** [comment]
@rmwalk 
 I've just uploaded my latest local commit into remote github , try it now , it seems to be fixed with me if i put it to sleep on battery , keep in touch

**Comment by rmwalk** [comment]
@Amin-0-1 Tried the latest commit but still same result. When I open the lid the keyboard light is back and apparently the system too because I hear the pling sounds when failing commands, but the screen is always dark and apparently doesn't turn back on.

**Comment by Amin-0-1** [comment]
@rmwalk do you have the same exact as my laptop g3 3590 9gen, if so, then try to update the bios to the latest version, if not then it is obvious cause it definitely has many differences in hardware

**Comment by rmwalk** [comment]
@Amin-0-1 yea I just noticed yours is an i7 while mine is an i5 lol other than that the specs are the same.

**Comment by Amin-0-1** [comment]
@rmwalk update your bios to latest version and give it a try , I don't think it's a big deal if you are I5 and mine is I7, now It seems that I have no problem with sleep on battery, the issue now is that it needs many keypress to wake that's all

**Comment by rmwalk** [comment]
@Amin-0-1 I just updated the bios and tried 3 times. At 1 time it was successful after pressing some keys many times, but the other 2 attempts didn't work so I had to force shutdown. But thats not a big deal at all, everything else works fine. Thanks for maintaining and updating the repo, it's very useful.
