### ISSUE TITLE
Sleep in non-charging state, wake up and shut down.

### ISSUE THREAD

**Issue by pyhpanyuahng** [Amin-0-1/hackintosh-Dell-g3-15-3590-#15]
Hello, Amin, I am your EFI user. During my use, I found that it failed to wake up when sleeping without charging. There is no sleep error when booting up.

Do you also have this problem? Or is there a solution to the problem?

**Comment by Amin-0-1** [comment]
It wakes from sleep on battery , meanwhile I have another issue which is also related to putting it into sleep while unpluged, which is "it wakes from sleep without no problem but sometimes it suddenly shuts down automatically , and booting up with no logs"
I think I've fixed it in my last commit , I am trying it right now , you can use my latest commit and notify me
