### ISSUE TITLE
External monitor 

### ISSUE THREAD

**Issue by Helmifran** [Amin-0-1/hackintosh-Dell-g3-15-3590-#16]
External monitor is not working with type c cable, have you tested it? on windows it works, but not on hackintosh.

**Comment by Amin-0-1** [comment]
it was working on Catalina, don't know why it is not working after upgrading to bigsur, and I have not time to find out what is the matter with it, if you got it notify me please

**Comment by Helmifran** [comment]
I tested today on the catalina with this EFI and the external monitor didn't work through the type c port, did you use another EFI to work the monitor?

**Comment by Amin-0-1** [comment]
try previous commits with the one that is is associated with catalina

**Comment by ghost** [comment]
I disabled SSDT-dGPU-Off.aml and added AAPL in DeviceProperties->Add->PciRoot(0x0)/Pci(0x2,0x0), ig-platform-id, the value is 0900A53E
You can use type-c to HDMI to connect to an external monitor

**Comment by ghost** [comment]
> I disabled SSDT-dGPU-Off.aml and added AAPL in DeviceProperties->Add->PciRoot(0x0)/Pci(0x2,0x0), ig-platform-id, the value is 0900A53E
> You can use type-c to HDMI to connect to an external monitor

BUT i can't use touchPad

**Comment by DANTHK** [comment]
> I disabled SSDT-dGPU-Off.aml and added AAPL in DeviceProperties->Add->PciRoot(0x0)/Pci(0x2,0x0), ig-platform-id, the value is 0900A53E
> You can use type-c to HDMI to connect to an external monitor

NICE! I can use type-c to HDMI, but brightness doesn't work...Could you give me some suggesstion?
