### ISSUE TITLE
Report on the use of OpenCORE in Mac OS 11.3.1

### ISSUE THREAD

**Issue by KuroseReza** [Amin-0-1/hackintosh-Dell-g3-15-3590-#17]
I used your OpenCORE in Mac OS 11.3.1. At present, there is no problem with WiFi and touchpad, but when I use Bluetooth, I can scan nearby Bluetooth devices and The use of Bluetooth headsets is not affected, but I can't transfer files

**Comment by Amin-0-1** [comment]
regarding the Bluetooth device, I've the same issue with my headset I don't know what the problem till now, so I'm using AUX
