### ISSUE TITLE
Can you fix the hdmi external monitor?

### ISSUE THREAD

**Issue by jetzchina** [Amin-0-1/hackintosh-Dell-g3-15-3590-#18]
Hi,This is important,can you fix the hdmi external monitor?

**Comment by DANTHK** [comment]
Could you fix the hdmi external monitor or can I use external monitor by USB docking station?

**Comment by Amin-0-1** [comment]
Sorry for being late, I really don't have the time to figure out what is the problem with the external monitor, it was working on Catalina, after upgrading to bigSur it does not work, Whenever I got the issue I will let you know

**Comment by DANTHK** [comment]
> Sorry for being late, I really don't have the time to figure out what is the problem with the external monitor, it was working on Catalina, after upgrading to bigSur it does not work, Whenever I got the issue I will let you know

Thank you for your reply. I'm currently using type-c to hdmi.

**Comment by Amin-0-1** [comment]
@DANTHK Then what is your problem? .. the HDMI port won't work as it is connected to a Nvidia graphics card which is not supported, About the type-c how did you make it work, It flickers with me not working at all

**Comment by DANTHK** [comment]
> @DANTHK那你的问题是什么？.. HDMI 端口无法工作，因为它连接到不受支持的 Nvidia 显卡，关于 type-c，你是如何使它工作的，它闪烁，我根本无法工作

I refer to another open issue. (#16 @rayku-chans)But brightness doesn't work.

**Comment by DANTHK** [comment]
> @DANTHK Then what is your problem? .. the HDMI port won't work as it is connected to a Nvidia graphics card which is not supported, About the type-c how did you make it work, It flickers with me not working at all

I referred to another open issue. (#16 @rayku-chans)But brightness doesn't work.
![image](https://user-images.githubusercontent.com/52982972/125547610-fdb089a9-393f-4ed7-bec9-16d41eb7c4c2.png)

**Comment by Amin-0-1** [comment]
It seems like you are on Catalina not big sur , is that right ?!

**Comment by DANTHK** [comment]
> It seems like you are on Catalina not big sur , is that right ?!

![image](https://user-images.githubusercontent.com/52982972/125591671-f03792ca-ad6d-4190-b777-43d148d409e8.png)
Oh, you must to disable SSDT-dGPU-off.aml...
![image](https://user-images.githubusercontent.com/52982972/125592138-c3554598-4ebd-43e6-a3e5-29e7a850e5f8.png)
I'm sorry about that.:)

**Comment by Amin-0-1** [comment]
dear @DANTHK it is not acceptable you disable that ssdt as it is for disabling dgpu, even if it makes external monitor work, it will turn your machine into something you can grill stick on it

**Comment by DANTHK** [comment]
> dear @DANTHK it is not acceptable you disable that ssdt as it is for disabling dgpu, even if it makes external monitor work, it will turn your machine into something you can grill stick on it

:(

**Comment by jetzchina** [comment]
@DANTHK @Amin-0-1  hi, thanks for your kind reply.i think i had find the way out .it doesn't need to disable that ssdt-dBGU-Off, just change the product version to MacBookPro13 ,don't use  MacBookPro16.
