### ISSUE TITLE
macOS Monterey 12.0.1 can‘t work.

### ISSUE THREAD

**Issue by TakimuraRen** [Amin-0-1/hackintosh-Dell-g3-15-3590-#19]
I'm going to upgrade macOS Monterey 12.0.1.
But I failed,It doesn't work properly.
Yours OC 0.7.1 is very very good. Can you upgrade OC?

**Comment by Amin-0-1** [comment]
I will update the repo and upgrade to Monterey whenever I have the time to do that, sorry but I'm kinda busy those days working, keep in touch

**Comment by TakimuraRen** [comment]
> I will update the repo and upgrade to Monterey whenever I have the time to do that, sorry but I'm kinda busy those days working, keep in touch

thanks you guy!

**Comment by logistones** [comment]
Hi Amin nice repo works great with Big Sur!
 tried with monterey but it doesnt work properly! any way, thanks for your work!

> I will update the repo and upgrade to Monterey whenever I have the time to do that, sorry but I'm kinda busy those days working, keep in touch

Hell Yeah!  thanks

**Comment by Mihaidev-cloud** [comment]
so there isn't any chances to make a monterey update because im stuck at "a required firmware update could not be installed"

**Comment by renantd** [comment]
I managed to install Monterey 12.5. but bluetooth and external monitor still don't work.
![monterey](https://user-images.githubusercontent.com/63022300/185496735-a438d2df-0484-4302-a14d-737d3bf9be3f.jpg)

**Comment by ducnmhn** [comment]
@renantd Can you share your EFI ?

**Comment by Amin-0-1** [comment]
@renantd 
I've installed Montery , I will upload the Latest EFI files today , I'm trying to get arround the Bluetooth newly issues, and also the external monitor, Wish me good luck, Thank you

**Comment by RenanCostaSilva** [comment]
Sorry I'm late. I've had a lot of work lately. I just updated the kexts , I used the same EFI and it uses the Montorey.raw image from the orarila site. I'm rooting @Amin-0-1 , and hoping the hdmi port is not controlled by the video card.

**Comment by Amin-0-1** [comment]
@RenanCostaSilva USBC is connected to Intel card not Nividia one, I'm sure of that, the HDIM worked for me on Catalina, in BigSur and above it need to repatch the framebuffere from whatevergreen site, it is a little bit of hard patching process, I'm trying

**Comment by Amin-0-1** [comment]
@renantd bluetooth working with me, please check the latest update on the repo

**Comment by RenanCostaSilva** [comment]
Ok, I got it . I will do a clean install this weekend and test. And take the opportunity to test with Ventura 13 Beta 6.
