### ISSUE TITLE
How to patch i2c touchpad?

### ISSUE THREAD

**Issue by ghost** [Amin-0-1/hackintosh-Dell-g3-15-3590-#2]

**Comment by Amin-0-1** [comment]
try to use my dsdt patch

**Comment by Amin-0-1** [comment]
i think it wont work on mojave also you have to be in the same bios version that i have

**Comment by Amin-0-1** [comment]
I made the touchpad working with a clean dsdt , now I am trying to transform it to an ssdt as I am transforming from clover to OC , when I manage to do that , I will notify you

**Comment by Amin-0-1** [comment]
@shadowsss I made SSDTs patched for touchpad , it is working okay now , if you want to give it a look
