### ISSUE TITLE
Airdrops not working

### ISSUE THREAD

**Issue by rafae2k** [Amin-0-1/hackintosh-Dell-g3-15-3590-#21]
Hello amin, i'm using the same intel 9560 board but airdrop and continuity doesn't work.

Want to know if its working for you on your setup, and ask if [itlwm](https://openintelwireless.github.io/itlwm/#download) is a way to fix it.

tks.

**Comment by rafae2k** [comment]
I just sign out and sign in on my apple id account and it works know!

Tks.

**Comment by alisonsilvabt** [comment]
Hey @rafae2k, I already logged out and logged back in to my account, but my airdrop does not appear and is found on other devices. Did you do any specific procedure?

**Comment by Amin-0-1** [comment]
@rafae2k 
@alisonsilvabt 
The itlwm docs itself says it is not working, it is opened but no connects

**Comment by rafae2k** [comment]
@alisonsilvabt Airdrop doesn't work only continuity works, it's been a while since i had my Hackintosh, but now i have an M1
