### ISSUE TITLE
External Monitor with type c cable not working

### ISSUE THREAD

**Issue by ducnmhn** [Amin-0-1/hackintosh-Dell-g3-15-3590-#23]
I tried use cable "type C to VGA" to output external monitor but didn't work. Everything is perfect when I used this cable  on Windows 10. 

I tried fix it but not work
https://github.com/Amin-0-1/hackintosh-Dell-g3-15-3590-/issues/18
https://github.com/Amin-0-1/hackintosh-Dell-g3-15-3590-/issues/16

Anyone can help ?

**Comment by Amin-0-1** [comment]
Unfortunately It is not working with me too in the latest os versions, It was working up untile cataline , I will try to figure it out soon once I come back to hackintosh , Good luck

**Comment by Amin-0-1** [comment]
@ducnmhn 
hey dude, how are your, I'm backing to hackintosh, any updates or news about the issue ?

**Comment by Amin-0-1** [comment]
@ducnmhn hi there, dude now the hdmi and external monitor is working okay , good luck
