### ISSUE TITLE
I can't wake up my mac！

### ISSUE THREAD

**Issue by TakimuraRen** [Amin-0-1/hackintosh-Dell-g3-15-3590-#24]
There's no way to wake up the laptop when I close the lid of my laptop.It has a black screen, and no matter what button is pressed, it has no effect.

**Comment by Amin-0-1** [comment]
it is working with me , make sure that your machine is the same as mine , mine is 3590 9th gen

**Comment by TakimuraRen** [comment]
yes,mine is 3590 9th gen too. it is always black and NOTEBOOK FAN ‘s sound is Very loud.
