### ISSUE TITLE
Trackpad

### ISSUE THREAD

**Issue by Enjoy-Combi** [Amin-0-1/hackintosh-Dell-g3-15-3590-#25]
Hello,

Can't get the trackpad working. Could you please detail the way to fix this or a link to the documentation to be followed.
Many thanks

**Comment by Enjoy-Combi** [comment]
Hi,

I went to the gpio pinning guide & didn't get the trackpad working yet. Will share it once getting fixed.
Into you ACPI (EFI folder) I do not see any ssdt for the gpio pinning. Am I right ?

**Comment by Amin-0-1** [comment]
Hello, 

Sorry for late respond, Unfortunately I'm a little bit away from hackintosh nowadays , But I will comeback to it soon may be in the next couple of days, I will upday the repo , regarding the touchpad It has a little issues I know , but I was able to makeing it work with the TPDX ssdt path, the gpio pinning way did not work with me

**Comment by Enjoy-Combi** [comment]
Many thanks,

For your information, in parallel I asked for help here : https://github.com/VoodooI2C/VoodooI2C/issues/515#issue-1340557768
I keep you in touch if getting some imporvements

**Comment by Enjoy-Combi** [comment]
Hi,

Any news for this issue ?

**Comment by Amin-0-1** [comment]
@Enjoy-Combi 
Hello Dude, regarding the touchpad, I found no problem with it currently on montery , while I was using the previous version of macos it was somehow not working sometimes, but now It's working with me like a charm, I will upload the latest OC version today after finishing some staff on the configuration, thank you

**Comment by Amin-0-1** [comment]
@Enjoy-Combi I found that touchpad is working perfect in montery

**Comment by Enjoy-Combi** [comment]
OK, thank you. Will investigate with your EFI and see the outcomes. Many thanks.

**Comment by Enjoy-Combi** [comment]
Working good with your efi. I just had to diasble CPUFirend as I don't have the same processor and all good. Your USB map is just a little bit different than mine (I have used USBtool and get USB3 for HS1 instead USB2 in yours).
I don't know which SSDT was able to correctly map the trackpad. Curious to understand this.
Anyway, many thanks !

**Comment by Amin-0-1** [comment]
note that if you have another version from dell g3 you have to redo the ssdt for mapping your ports correclty , here is the ssdt for mine SSDT-UIAC, you can follow along with that guide , and be patient https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html
regarding the touchpad patch it is SSDT-TPDX
