### ISSUE TITLE
USB-C don't work

### ISSUE THREAD

**Issue by haunetal1990** [Amin-0-1/hackintosh-Dell-g3-15-3590-#27]
Hey, my USB-C don't work on the Dell G3 3590 Laptop. My Bluetooth works, but I can't connect to my iPhone. My iPhone says like:  will not be accepted.
And the HDMI don't work haha

**Comment by Amin-0-1** [comment]
the hdmi was working from the beginning, now you can check the usb c too, about the iphone in bluetooth I don't really know how to fix it, if you do please help

**Comment by Amin-0-1** [comment]
I think this problem is not related to hackintosh
see this https://discussions.apple.com/thread/253307153
