### ISSUE TITLE
USB HUB PORTS DO NOT WORK ON USB-C

### ISSUE THREAD

**Issue by alisonsilvabt** [Amin-0-1/hackintosh-Dell-g3-15-3590-#28]
Hello, I'm using EFI but when trying to use a usb-c hub I can't use the USB ports, except the HDMI output (this works). Has anyone ever had this problem? How do I map?

**Comment by haunetal1990** [comment]
have the same problem. My Hub works, but only for HDMI Output.

**Comment by alisonsilvabt** [comment]
Maybe I'm wrong (and I hope so), but from what I understand to map the USB-C as HUB, the usb ports can work, but the HDMI doesn't....

**Comment by haunetal1990** [comment]
edit*
the complete hub isn't on hackintool. don't know why.

**Comment by Amin-0-1** [comment]
hello dears, I'm working on it now, I will fix the usb c beside the hdmi which is already working, wish me good luck, see you

**Comment by haunetal1990** [comment]
good luck

**Comment by Amin-0-1** [comment]
check the usb c now

**Comment by haunetal1990** [comment]
looks good. Thanks. My hub has 4 USB (2x usb 3.0 + 2x usb 2.0) + 1 USB-c + 2 HDMI + SD card 

works:
- 2x USB 3.0
- 2x HDMI

didn't work
- 2x USB 2.0
- HDMI sound
- USB-C

not tested:
- SD card

if i didn't use the hub, so only the usb-c i can load only my ipad..

**Comment by Amin-0-1** [comment]
My hub works in usb2 an usb 3 ports I've tested all of them and mapped ocrrectly to be switched between usb2 and 3 for very usb you plug into the hub, SD and usbc not tested also

**Comment by haunetal1990** [comment]
Which tool did u use? hackintool? o_O or which on?

**Comment by Amin-0-1** [comment]
yeap hackintool

**Comment by haunetal1990** [comment]
hm, cause i used that Program and didn't show the hub xD

**Comment by Amin-0-1** [comment]
look here, it's connected to the ss and hs which are the usb2 ports and usb3 ports
[Screen Shot 2022-09-10 at 10.35.31 PM.zip](https://github.com/Amin-0-1/hackintosh-Dell-g3-15-3590-/files/9541377/Screen.Shot.2022-09-10.at.10.35.31.PM.zip)

**Comment by haunetal1990** [comment]
nice, looks great.

**Comment by haunetal1990** [comment]
so I found a way.
standard usb-c : works - I can see the iPad over "Finder" + charge the iPad
Hub: 4 USB (2x 3.0 + 2x 3.0) works 
the other side from the hub (HDMI, USB-C, ..) didn't work.

I used that tool on windows:
https://www.reddit.com/r/hackintosh/comments/n2udl3/usbtoolboxᵇᵉᵗᵃ_making_usb_mapping_simpler/?utm_source=amp&utm_medium=&utm_content=post_body

Maybe you become a better result.

**Comment by Amin-0-1** [comment]
Trust me I made each and everything in that repo in a good way and with a great focusing, I've spent lots of time just to learn how to make that machine as perfect as much I can, as it wasn't so easy in the beginning for that damn machine, it gives me lots of pain, so that is all I have, my USB_C hub works with 2 usb3 and 1 usb2 and also the hdmi, the only weird thing I'm facing is that when you unplug the hub and replug it is not detected, you have to wait a couple of minutes, I don't know if it is a global issue or it's my hub problem

**Comment by haunetal1990** [comment]
Did you use that tool that i post to? Cause with the new kext file i can use my hub and can unplug it and seconds later i can plug it and its detected.. 
You make a great job. I can send you my files and maybe you can make it better ?

**Comment by Amin-0-1** [comment]
I made it as dortania guide says, If you have any problem just tell me I will help, and my efi is now the most that I've reached in everything

**Comment by alisonsilvabt** [comment]
@haunetal1990 If this is the case, create a repository with your own EFI, since in your case there were particularities

(I would like to test it, since I have not yet been able to use the usb ports of my hub)

**Comment by Amin-0-1** [comment]
@haunetal1990 
send me your generated kexts for the method that you've mentioned, I'll try to figure it out, thanks

**Comment by haunetal1990** [comment]
[https://github.com/haunetal1990/Hackintosh_Dell_G3_3590_USB_Map](url) 
i know now why i can't use the USB-C on my Hub. it doesn't work on windows to.

**Comment by Amin-0-1** [comment]
@haunetal1990 be careful you've disabled bluetooth with that mapping, double check it

**Comment by Amin-0-1** [comment]
the result as the same with my ssdt patch

**Comment by haunetal1990** [comment]
Why i musst disable the bluetooth ?

hm okay, bad, cause with your ssdt i can only charge my ipad over usb-c. With my kext file i can charge and find it over finder.

thanks for checking

**Comment by Amin-0-1** [comment]
I edited your kext files or generated another one that works perfect you can check it from my repo

**Comment by haunetal1990** [comment]
can you explain why did u edit the smbios on your efi?
thanks for your work

**Comment by Amin-0-1** [comment]
As am testing the power management right now to reach the best state for a better performance, it seems that the 16,4 is better state from 16,1

**Comment by haunetal1990** [comment]
ah okay, thanks :)

**Comment by alisonsilvabt** [comment]
@Amin-0-1  I tested your latest version of the EFI and it's working perfectly on my machine, including the HUB with 3 USB 2.0 ports (I couldn't use the USBC from the HUB but that's not important to me) and the HDMI.

However, my WIFI stopped working, being able to access internet only by cable. Did you have this problem too?

**Comment by haunetal1990** [comment]
Morning,
@alisonsilvabt did u make a restart? Cause sometime i have problems with the mousepad and a restart was good for me.

i‘ve checked the efi and power management. On my Dell G3 i have the same power with 16.1 or 16.4.

**Comment by Amin-0-1** [comment]
@alisonsilvabt 
no the wifi is working perfecly with me

**Comment by alisonsilvabt** [comment]
I managed to solve. When trying to implement the changes from the commit, I made each change, I think I must have broken something. Finally, I copied and pasted everything and just changed the "generic" data and it worked. With that I think we can end this discussion.
