### ISSUE TITLE
Intel AC9560 Bluetooth Connection failed

### ISSUE THREAD

**Issue by haunetal1990** [Amin-0-1/hackintosh-Dell-g3-15-3590-#29]
My iPhone / iPad can't connection to my Laptop. iPad and iPhone shows the error: Connection failed.
Can you help me please?

**Comment by Amin-0-1** [comment]
I think this problem is not related to hackintosh
see this https://discussions.apple.com/thread/253307153

**Comment by haunetal1990** [comment]
fail, cause i have iOS16 and same problem. very fail from apple

**Comment by haunetal1990** [comment]
I have now the Problem preference pane can't load Bluetooth *lol* -.- Have you maybe a tipp to fix that problem, please?
