### ISSUE TITLE
Is the GPU working?

### ISSUE THREAD

**Issue by gabemule** [Amin-0-1/hackintosh-Dell-g3-15-3590-#3]
Hi, is the GPU working? o_O

**Comment by Amin-0-1** [comment]
yeap all things working right now , except only the internal microphone and surly the full internal wifi support like airdrop , there is a new kexts under development i think it will come up soon to be support let us see , it working now as a beta i tried it working and bluetooth also working

**Comment by Amin-0-1** [comment]
I made the touchpad working with a clean dsdt , now I am trying to transform it to an ssdt as I am transforming from clover to OC , when I manage to do that , I will notify you
