### ISSUE TITLE
Have you ever run into the problem of not loading the sound card when you turn on the computer ？

### ISSUE THREAD

**Issue by dxide** [Amin-0-1/hackintosh-Dell-g3-15-3590-#6]

**Comment by Amin-0-1** [comment]
sometimes it is not loading, I don't know why

**Comment by dxide** [comment]
> sometimes it is not loading, I don't know why

use OC also have this problem ?

**Comment by Amin-0-1** [comment]
sometimes

**Comment by Amin-0-1** [comment]
@Dxide add alcdelay = 1000 in the boot arg (clover) or args(open core) it will fix the issue
