### ISSUE TITLE
 Could you please upload the complete EFI file?

### ISSUE THREAD

**Issue by DANTHK** [Amin-0-1/hackintosh-Dell-g3-15-3590-#8]
It seems to not work property on my laptop. 
I use it to replace the OC Flash Drive folder, but the laptop did not boot.

DELL G3 3590, it's the same as your computer. 

Thanks!

**Comment by zhaoxuan813** [comment]
&nbsp; 你好，你需要的是dell g3 3590装mac os的efi吗？
&nbsp; 最近因为我没有时间没有捣鼓这个，原来的efi我已经删除了重新装了windows，很抱歉没能够帮助你





发自我的iPhone


------------------ Original ------------------

**Comment by haojianying-HJY** [comment]
OC doesn't boot in my computer either.But clover boot successfully.You can try it.👍

**Comment by DANTHK** [comment]
> OC doesn't boot in my computer either.But clover boot successfully.You can try it.👍



> &nbsp; 你好，你需要的是dell g3 3590装mac os的efi吗？ &nbsp; 最近因为我没有时间没有捣鼓这个，原来的efi我已经删除了重新装了windows，很抱歉没能够帮助你 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: DANTHK <notifications@github.com&gt; Date: Mon,Nov 16,2020 9:31 AM Cc: Subscribed <subscribed@noreply.github.com&gt; Subject: Re: [Amin-0-1/hackintosh-Dell-g3-15-3590-] Could you please upload the complete EFI file? (#8) It seems to not work property on my laptop. I use it to replace the OC Flash Drive folder, but the laptop did not boot. DELL G3 3590, it's the same as your computer. Thanks! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.


> OC doesn't boot in my computer either.But clover boot successfully.You can try it.👍

**Comment by DANTHK** [comment]
> > OC也无法在我的计算机中启动，但是三叶草启动成功。您可以尝试。👍
> 
> > 你好，你需要的是dell g3 3590装mac os的efi吗？最近因为我没有时间没有捣鼓这个，原来的efi我已经删除了重新装了窗户，很抱歉没能够帮助你发自自我的iPhone 
> > […](#) 
> > - -----------------原始------------------发件人：DANTHK < [notifications@github.com](mailto:notifications@github.com) >日期：星期一， 2020年11月16日上午9:31抄送：订阅< [subscribed@noreply.github.com](mailto:subscribed@noreply.github.com) >主题：回复：[Amin-0-1 / hackintosh-Dell-g3-15-3590-]您能否上传完整的EFI文件？（[＃8](https://github.com/Amin-0-1/hackintosh-Dell-g3-15-3590-/issues/8)）我的笔记本电脑似乎不工作。我用它替换了OC Flash Drive文件夹，但是笔记本电脑没有启动。DELL G3 3590，与您的计算机相同。谢谢！—您收到此消息是因为您已订阅该线程。直接回复此电子邮件，在GitHub上查看或取消订阅。
> 
> > OC也无法在我的计算机中启动，但是三叶草启动成功。您可以尝试。👍

我已经尝试过三叶草，最近打算向OC过渡。谢谢您的回答

**Comment by DANTHK** [comment]
> > OC也无法在我的计算机中启动，但是三叶草启动成功。您可以尝试。👍
> 
> > 你好，你需要的是dell g3 3590装mac os的efi吗？最近因为我没有时间没有捣鼓这个，原来的efi我已经删除了重新装了窗户，很抱歉没能够帮助你发自自我的iPhone 
> > […](#) 
> > - -----------------原始------------------发件人：DANTHK < [notifications@github.com](mailto:notifications@github.com) >日期：星期一， 2020年11月16日上午9:31抄送：订阅< [subscribed@noreply.github.com](mailto:subscribed@noreply.github.com) >主题：回复：[Amin-0-1 / hackintosh-Dell-g3-15-3590-]您能否上传完整的EFI文件？（[＃8](https://github.com/Amin-0-1/hackintosh-Dell-g3-15-3590-/issues/8)）我的笔记本电脑似乎不工作。我用它替换了OC Flash Drive文件夹，但是笔记本电脑没有启动。DELL G3 3590，与您的计算机相同。谢谢！—您收到此消息是因为您已订阅该线程。直接回复此电子邮件，在GitHub上查看或取消订阅。
> 
> > OC也无法在我的计算机中启动，但是三叶草启动成功。您可以尝试。👍



> &nbsp; 你好，你需要的是dell g3 3590装mac os的efi吗？ &nbsp; 最近因为我没有时间没有捣鼓这个，原来的efi我已经删除了重新装了windows，很抱歉没能够帮助你 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: DANTHK <notifications@github.com&gt; Date: Mon,Nov 16,2020 9:31 AM Cc: Subscribed <subscribed@noreply.github.com&gt; Subject: Re: [Amin-0-1/hackintosh-Dell-g3-15-3590-] Could you please upload the complete EFI file? (#8) It seems to not work property on my laptop. I use it to replace the OC Flash Drive folder, but the laptop did not boot. DELL G3 3590, it's the same as your computer. Thanks! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没关系，谢谢
