### ISSUE TITLE
Help upgrading to 0.6.4 - Only bluetooth won't work

### ISSUE THREAD

**Issue by joaolevysa** [Amin-0-1/hackintosh-Dell-g3-15-3590-#9]
Hey, Amin!
Can you please help me with this one?
I'm upgrading to OC 0.6.4, already booting and everything works fine. I'll try to upgrade to Big Sur.
But I can't seem to get the bluetooth working. Mine is the qualcomm version (G3 3590 i5 9th)
With your EFI (0.6.0) it works. But I can't find what is missing.
Thank you!
[EFI.zip](https://github.com/Amin-0-1/hackintosh-Dell-g3-15-3590-/files/5663370/EFI.zip)

**Comment by gundogdufurkan** [comment]
> Hey, Amin!
> Can you please help me with this one?
> I'm upgrading to OC 0.6.4, already booting and everything works fine. I'll try to upgrade to Big Sur.
> But I can't seem to get the bluetooth working. Mine is the qualcomm version (G3 3590 i5 9th)
> With your EFI (0.6.0) it works. But I can't find what is missing.
> Thank you!
> [EFI.zip](https://github.com/Amin-0-1/hackintosh-Dell-g3-15-3590-/files/5663370/EFI.zip)

Hey I am new at hackintoshing. I have the same laptop g3 3590 i5 9th. Can i use your EFI file booting usb without doing guide steps? If i copy the EFI files i can't boot the usb at start. Can you help me?

**Comment by Amin-0-1** [comment]
sorry for being late, what about now ?
